//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCAL.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCAL.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD	Andorra
        ///AE	United Arab Emirates
        ///AF	Afghanistan
        ///AG	Antigua
        ///AL	Albania
        ///AM	Armenia
        ///AN	Curacao
        ///AO	Angola
        ///AR	Argentina
        ///AS	American Samoa
        ///AT	Austria
        ///AU	Australia
        ///AW	Aruba
        ///AZ	Azerbaijan
        ///BA	Bosnia and Herzegovina
        ///BB	Barbados
        ///BD	Bangladesh
        ///BE	Belgium
        ///BF	Burkina Faso
        ///BG	Bulgaria
        ///BH	Bahrain
        ///BI	Burundi
        ///BJ	Benin
        ///BL	Guadeloupe
        ///BN	Brunei
        ///BO	Bolivia
        ///BR	Brazil
        ///BS	Bahamas
        ///BT	Bhutan
        ///BW	Botswana
        ///BY	Belarus
        ///BZ	Belize
        ///CA	Canada
        ///CD	Democratic Republic of the Congo
        ///CF	Central African Republic
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type	Class	Masa	Tithi	Visible	Fast Subject	Text	FastType	Used	Start Year	Spec	SpecRef	Sanskranti	Offset
        ///T	3	0	6	1		Sri Abhirama Thakura -- Disappearance	0	1	-10000				
        ///T	3	0	9	1		Srila Vrndavana Dasa Thakura -- Disappearance	0	1	-10000				
        ///T	3	0	14	1		Sri Gadadhara Pandita -- Appearance	0	1	-10000				
        ///T	1	0	17	1		Aksaya Trtiya. Candana Yatra starts. (Continues for 21 days)	0	1	-10000				
        ///T	5	0	21	1		Jahnu Saptami	0	1	-10000				
        ///T	1	0	23	1		Srimati Sita Devi (consort of Lord Sri Rama) -- Appearance	0	1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sant Julia de Loria	42.4637237	1.491286755	AD	Europe/Andorra						
        ///les Escaldes	42.50728696	1.534137726	AD	Europe/Andorra						
        ///la Massana	42.54498667	1.514825821	AD	Europe/Andorra						
        ///Umm al Qaywayn	25.5652778	55.5533333	AE	Asia/Dubai						
        ///Ra&apos;s al Khaymah	25.7911111	55.9427778	AE	Asia/Dubai						
        ///Khawr Fakkan	25.3391667	56.3561111	AE	Asia/Dubai						
        ///Dubai	25.2522222	55.28	AE	Asia/Dubai						
        ///Sharjah	25.3622222	55.3911111	AE	Asia/Dubai						
        ///Al `Ayn	24.1916667	55.7605556	AE	Asia/Dubai						
        ///Ajm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to note	text	key	comment	
        ///0	Sunday	Weekday.0.Full		
        ///1	Monday			
        ///2	Tuesday			
        ///3	Wednesday			
        ///4	Thursday			
        ///5	Friday			
        ///6	Saturday			
        ///7	Date			
        ///8	Time			
        ///9	Location			
        ///10	Latitude			
        ///11	Longitude			
        ///12	Timezone			
        ///13	Tithi			
        ///14	Tithi Elaps.			
        ///15	Naksatra			
        ///16	Naksatra Elaps.			
        ///17	Child Name Suggestions			
        ///18	(according naksatra)			
        ///19	(according rasi)			
        ///20	Paksa			
        ///21	(during Purusottama Adhika Masa)			
        ///22	Masa			
        ///23	Gaurabda Year			
        ///24	Celebrations			
        ///25	Appearance Day Calculation [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Strings {
            get {
                return ResourceManager.GetString("Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///  &lt;timezone_list&gt;
        ///    &lt;timezone&gt;
        ///      &lt;name&gt;Africa/Abidjan&lt;/name&gt;
        ///      &lt;transition date=&quot;2012-08-07 20:16:36 +0000&quot; offset=&quot;0&quot; abbr=&quot;GMT&quot; dst=&quot;0&quot; /&gt;
        ///    &lt;/timezone&gt;
        ///    &lt;timezone&gt;
        ///      &lt;name&gt;Africa/Accra&lt;/name&gt;
        ///      &lt;transition date=&quot;2012-08-07 20:16:36 +0000&quot; offset=&quot;0&quot; abbr=&quot;GMT&quot; dst=&quot;0&quot; /&gt;
        ///    &lt;/timezone&gt;
        ///    &lt;timezone&gt;
        ///      &lt;name&gt;Africa/Addis_Ababa&lt;/name&gt;
        ///      &lt;transition date=&quot;2012-08-07 20:16:36 +0000&quot; offset=&quot;10800&quot; abbr=&quot;EAT&quot; dst=&quot;0&quot; /&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Timezones {
            get {
                return ResourceManager.GetString("Timezones", resourceCulture);
            }
        }
    }
}
