//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCAL.Base.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GCAL.Base.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD	Andorra
        ///AE	United Arab Emirates
        ///AF	Afghanistan
        ///AG	Antigua
        ///AL	Albania
        ///AM	Armenia
        ///AN	Curacao
        ///AO	Angola
        ///AR	Argentina
        ///AS	American Samoa
        ///AT	Austria
        ///AU	Australia
        ///AW	Aruba
        ///AZ	Azerbaijan
        ///BA	Bosnia and Herzegovina
        ///BB	Barbados
        ///BD	Bangladesh
        ///BE	Belgium
        ///BF	Burkina Faso
        ///BG	Bulgaria
        ///BH	Bahrain
        ///BI	Burundi
        ///BJ	Benin
        ///BL	Guadeloupe
        ///BN	Brunei
        ///BO	Bolivia
        ///BR	Brazil
        ///BS	Bahamas
        ///BT	Bhutan
        ///BW	Botswana
        ///BY	Belarus
        ///BZ	Belize
        ///CA	Canada
        ///CD	Democratic Republic of the Congo
        ///CF	Central African Republic
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD	Europe/Andorra
        ///AE	Asia/Dubai
        ///AF	Asia/Kabul
        ///AG	America/Antigua
        ///AL	Europe/Tirane
        ///AM	Asia/Yerevan
        ///AN	America/Curacao
        ///AO	Africa/Luanda
        ///AR	America/Argentina/Buenos_Aires
        ///AR	America/Argentina/Cordoba
        ///AR	America/Argentina/Jujuy
        ///AR	America/Argentina/Mendoza
        ///AR	America/Argentina/San_Juan
        ///AR	America/Argentina/Tucuman
        ///AS	Pacific/Pago_Pago
        ///AT	Europe/Vienna
        ///AU	Australia/Adelaide
        ///AU	Australia/Brisbane
        ///AU	Australia/Melbourne
        ///AU	Australia/Perth
        ///AU	Australia/Sydney
        ///AW	America/Aruba
        ///AZ	Asia/Baku
        ///BA	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountryTimezones {
            get {
                return ResourceManager.GetString("CountryTimezones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;events nextid=&quot;500&quot;&gt;
        ///  &lt;event type=&quot;TITHI&quot; class=&quot;3&quot; visible=&quot;1&quot; used=&quot;1&quot;&gt;
        ///    &lt;fastsubject&gt;
        ///    &lt;/fastsubject&gt;
        ///    &lt;startyear&gt;-10000&lt;/startyear&gt;
        ///    &lt;specid&gt;0&lt;/specid&gt;
        ///    &lt;offset&gt;0&lt;/offset&gt;
        ///    &lt;deleted&gt;0&lt;/deleted&gt;
        ///    &lt;text&gt;Sri Abhirama Thakura -- Disappearance&lt;/text&gt;
        ///    &lt;eventid&gt;2&lt;/eventid&gt;
        ///    &lt;fasttype&gt;0&lt;/fasttype&gt;
        ///    &lt;tithi&gt;6&lt;/tithi&gt;
        ///    &lt;masa&gt;0&lt;/masa&gt;
        ///  &lt;/event&gt;
        ///  &lt;event type=&quot;TITHI&quot; class=&quot;3&quot; visible=&quot;1&quot; used=&quot;1&quot;&gt;
        ///    &lt;fastsubject&gt;
        ///    &lt;/fa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sant Julia de Loria	42.4637237	1.491286755	AD	Europe/Andorra						
        ///les Escaldes	42.50728696	1.534137726	AD	Europe/Andorra						
        ///la Massana	42.54498667	1.514825821	AD	Europe/Andorra						
        ///Umm al Qaywayn	25.5652778	55.5533333	AE	Asia/Dubai						
        ///Ra&apos;s al Khaymah	25.7911111	55.9427778	AE	Asia/Dubai						
        ///Khawr Fakkan	25.3391667	56.3561111	AE	Asia/Dubai						
        ///Dubai	25.2522222	55.28	AE	Asia/Dubai						
        ///Sharjah	25.3622222	55.3911111	AE	Asia/Dubai						
        ///Al `Ayn	24.1916667	55.7605556	AE	Asia/Dubai						
        ///Ajm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lang	English
        ///langid	2
        ///0	Sunday	Weekday.0.Full		Sunday
        ///1	Monday			Monday
        ///2	Tuesday			Tuesday
        ///3	Wednesday			Wednesday
        ///4	Thursday			Thursday
        ///5	Friday			Friday
        ///6	Saturday			Saturday
        ///7	Date			Date
        ///8	Time			Time
        ///9	Location			Location
        ///10	Latitude			Latitude
        ///11	Longitude			Longitude
        ///12	Timezone			Timezone
        ///13	Tithi			Tithi
        ///14	Tithi Elaps.			Tithi Elaps.
        ///15	Naksatra			Naksatra
        ///16	Naksatra Elaps.			Naksatra Elaps.
        ///17	Child Name Suggestions			Child Name Suggestions
        ///18	(according naksatra)			(accordi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Strings {
            get {
                return ResourceManager.GetString("Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;timezone_list&gt;
        ///  &lt;timezone normalAbbr=&quot;GMT&quot; dstAbbr=&quot;GMT&quot; offset=&quot;0&quot; dst=&quot;False&quot;&gt;
        ///    &lt;name&gt;Africa/Abidjan&lt;/name&gt;
        ///  &lt;/timezone&gt;
        ///  &lt;timezone normalAbbr=&quot;GMT&quot; dstAbbr=&quot;GMT&quot; offset=&quot;0&quot; dst=&quot;False&quot;&gt;
        ///    &lt;name&gt;Africa/Accra&lt;/name&gt;
        ///  &lt;/timezone&gt;
        ///  &lt;timezone normalAbbr=&quot;EAT&quot; dstAbbr=&quot;EAT&quot; offset=&quot;180&quot; dst=&quot;False&quot;&gt;
        ///    &lt;name&gt;Africa/Addis_Ababa&lt;/name&gt;
        ///  &lt;/timezone&gt;
        ///  &lt;timezone normalAbbr=&quot;CET&quot; dstAbbr=&quot;CET&quot; offset=&quot;60&quot; dst=&quot;False&quot;&gt;
        ///    &lt;name&gt;Africa/Algiers&lt;/name&gt;
        ///  &lt;/timezone&gt;
        ///  &lt;timezone normalAbbr=&quot;EA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Timezones {
            get {
                return ResourceManager.GetString("Timezones", resourceCulture);
            }
        }
    }
}
